CREATE TABLE gassydb.ReverbListing (
id int UNSIGNED AUTO_INCREMENT PRIMARY KEY,
ReverbId int,
Make VARCHAR(30), 
Model VARCHAR(30), 
ItemDescription VARCHAR(250),
ItemCondition VARCHAR(100),
Price DECIMAL(10, 2),
Shipping DECIMAL(10, 2),
OffersEnabled BOOLEAN ,
Link VARCHAR(250),
ListingCreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
ListingPublishedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);


