CREATE TABLE gassydb.listing (
id int UNSIGNED AUTO_INCREMENT PRIMARY KEY,
SiteId VARCHAR(30),
Make VARCHAR(30), 
Model VARCHAR(30), 
Price DECIMAL(10, 2),
CreatedAt DATETIME,
UpdatedAt DATETIME,
AddedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);
