CREATE TABLE gassydb.listing (
id int UNSIGNED AUTO_INCREMENT PRIMARY KEY,
SiteId VARCHAR(30),
Make VARCHAR(30), 
Model VARCHAR(30), 
ItemDescription VARCHAR(250),
ItemCondition VARCHAR(100),
Price DECIMAL(10, 2),
Shipping DECIMAL(10, 2),
OffersEnabled BOOLEAN ,
Link VARCHAR(250),
ListingCreatedAt DATETIME,
ListingUpdatedAt DATETIME,
UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
AddedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

