CREATE TABLE gassydb.WishlistItem (
id int UNSIGNED AUTO_INCREMENT PRIMARY KEY,
UserId int,
Make VARCHAR(30), 
Model VARCHAR(30), 
MinPrice DECIMAL(10, 2),
MaxPrice DECIMAL(10, 2),
CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);


