CREATE TABLE gassydb.WishlistItem (
Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
OwnerId INT,
Make VARCHAR(30), 
Model VARCHAR(30), 
MinPrice DECIMAL(10, 2),
MaxPrice DECIMAL(10, 2),
CategoryId INT,
CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
UNIQUE(Id),
INDEX(Id)
);


